#!/usr/bin/env bash
# Install nginx web server
#Redirection

sudo apt-get update
sudo apt-get install -y nginx

# Creat an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/wadenya permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
