#!/usr/bin/env bash
# Install nginx web server
#Redirection

apt-get -y update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /var/www/html/index.html
printf %s " server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index index.html index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUIwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
