#!/usr/bin/env bash
# Install nginx web server
#Redirection

apt-get -y update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/ngnix/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s " server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index index.html index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUIwu4;
	}

	error_page 404 /404.html;
	location /404 {
	root /etc/nginx/html;
	internal;
}" > /etc/nginx/sites-available/default

service nginx restart
