#!/usr/bin/env bash
#Double the number of webservers

var=$(hostname)
nwstrng1="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
nwstrng2="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

server_block_path="/etc/ngnix/sites-available/default"
if ! grep -q "add_header X-Served-By" "$server_block_path"; then
    sudo sed -i "/server_name -;/a \\\tadd_header X-Served-By \$hostname;" $server_block-path    v
fi

sudo systemctl start nginx
