#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

sudo apt update
sudo apt install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Configure HAProxy for web-01 and web-02 with roundrobin algorithm
haproxy_cfg="/etc/haproxy/haproxy.cfg"

# Append our configuration
cat <<EOL | sudo tee -a $haproxy_cfg

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend webservers

backend webservers
    balance roundrobin
    server 200656-web-01 3.89.160.21:80 check
    server 200656-web-02 54.197.132.144:80 check

EOL

sudo systemctl restart haproxy
