#!/usr/bin/env bash
#Nginx likes port

#cofig nginx to listen to port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart
service nginx start
#terminate fisrt nginx proc
kill "$(pgrep 'nginx' | head -1)"
