#!/usr/bin/env bash
#Indefinitely writes I am alive! to the file /tmp/my_process
#In btwn every I am alive! message, the program should pause for 2 sec
while true; do
	sudo bash -c 'echo "I am alive!" >> /tmp/my_process'
	sleep
done
