#!/usr/bin/env bash
#Bash script that display:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for c in *; do
	echo "$c" | cut -d '-' -f 2
done
